apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-uid
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true

  - name: Tempo
    type: tempo
    uid: tempo-uid
    access: proxy
    url: http://tempo:3200
    isDefault: true
    editable: true
    jsonData:
      tracesToMetrics:
        datasourceUid: 'prometheus-uid'
      serviceMap:
        datasourceUid: 'prometheus-uid'
      nodeGraph:
        enabled: true
